[workspace]
resolver = "2"
members = [
    "ratarmount",
    "ratarmount-core",
    "ratarmount-index",
    "ratarmount-fuse",
    "ratarmount-compress",
    "ratarmount-formats-tar",
    "ratarmount-formats-zip",
    "ratarmount-formats-ar",
    "ratarmount-formats-cpio",
    "ratarmount-formats-iso9660",
    "ratarmount-formats-warc",
    "ratarmount-formats-xar",
    "ratarmount-formats-cab",
    "ratarmount-formats-libarchive",
    "ratarmount-formats-sevenzip",
    "ratarmount-formats-sqlar",
    "ratarmount-formats-squashfs",
    "ratarmount-formats-ext4",
    "ratarmount-formats-fat",
    "ratarmount-formats-asar",
    "ratarmount-formats-ogg",
    "ratarmount-formats-html",
    "ratarmount-formats-pdf",
    "ratarmount-formats-git",
    "ratarmount-remote",
    "ratarmount-compositing",
]
default-members = ["ratarmount"]

[workspace.package]
version = "0.1.12"
edition = "2021"
license = "MIT"
repository = "https://github.com/mxmlnkn/ratarmount-rs"
rust-version = "1.74"

[workspace.dependencies]
ratarmount-core = { path = "ratarmount-core" }
ratarmount-index = { path = "ratarmount-index" }
ratarmount-fuse = { path = "ratarmount-fuse" }
ratarmount-compress = { path = "ratarmount-compress" }
ratarmount-formats-tar = { path = "ratarmount-formats-tar" }
ratarmount-formats-zip = { path = "ratarmount-formats-zip" }
ratarmount-formats-ar = { path = "ratarmount-formats-ar" }
ratarmount-formats-cpio = { path = "ratarmount-formats-cpio" }
ratarmount-formats-iso9660 = { path = "ratarmount-formats-iso9660" }
ratarmount-formats-warc = { path = "ratarmount-formats-warc" }
ratarmount-formats-xar = { path = "ratarmount-formats-xar" }
ratarmount-formats-cab = { path = "ratarmount-formats-cab" }
ratarmount-formats-libarchive = { path = "ratarmount-formats-libarchive" }
ratarmount-formats-sevenzip = { path = "ratarmount-formats-sevenzip" }
ratarmount-formats-sqlar = { path = "ratarmount-formats-sqlar" }
ratarmount-formats-squashfs = { path = "ratarmount-formats-squashfs" }
ratarmount-formats-ext4 = { path = "ratarmount-formats-ext4" }
ratarmount-formats-fat = { path = "ratarmount-formats-fat" }
ratarmount-formats-asar = { path = "ratarmount-formats-asar" }
ratarmount-formats-ogg = { path = "ratarmount-formats-ogg" }
ratarmount-formats-html = { path = "ratarmount-formats-html" }
ratarmount-formats-pdf = { path = "ratarmount-formats-pdf" }
ratarmount-formats-git = { path = "ratarmount-formats-git" }
ratarmount-remote = { path = "ratarmount-remote" }
ratarmount-compositing = { path = "ratarmount-compositing" }
rusqlite = { version = "0.32", features = ["bundled"] }
thiserror = "2"
clap = { version = "4", features = ["derive", "env"] }
libc = "0.2"
log = "0.4"
env_logger = "0.11"
tempfile = "3"
